title:                  Î»bje
description:            Thoughts on programming
github_username:        codebje
logo:                   site-logo.png
#url:              http://bje.id.au

# Owner/author information
owner:
  name:           Byron Ellacott
  avatar:         bio-photo.jpg

highlighter: pygments
markdown:    kramdown

permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

sass:
  cache_location: "/tmp/.sass-cache"
